version: '2'
services:
    apcmeetings-app:
        image: apcmeetings
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://apcmeetings-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=APCMeetings
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    apcmeetings-mongodb:
        extends:
            file: mongodb.yml
            service: apcmeetings-mongodb
